image_speed = 0;
baddieid = 449;
content = 0;
refresh = 20;
depth = 1;
hsp = 0;
vsp = 0;
grounded = 0;
grav = 0.5;
mask_index = spr_baddiespawner;
platformid = -4;
hsp_carry = 0;
scr_collision_init();
