event_inherited();
player_distance_threshold = 500;
ghost_distance_threshold = 400;
state = UnknownEnum.Value_0;
hsp = 0;
vsp = 0;
hsp_carry = 0;
scr_collision_init();
platformid = -4;
grounded = 0;
grav = 0.5;
