grav = 0;
hsp = 0;
vsp = 0;
grounded = 0;
image_speed = 0;
alarm[0] = 40;
global.panic = 0;
alarm[1] = 500;
platformid = -4;
hsp_carry = 0;
global.combo = 0;
global.comboscore = 0;
scr_collision_init();
