grabbed = 0;
hsp = 0;
vsp = 0;
grav = 0.5;
flash = 1;
hp = 0;
grounded = 1;
state = UnknownEnum.Value_0;
mask_index = spr_player_mask;
image_speed = 0.4;
depth = 1;
platformid = -4;
hsp_carry = 0;
scr_collision_init();
