grabbed = 0;
hsp = 0;
vsp = 0;
grav = 0.5;
flash = 1;
unpickable = 0;
hp = 0;
grounded = 1;
state = UnknownEnum.Value_0;
playerid = 245;
image_speed = 0;
image_index = random_range(0, image_number - 1);
mask_index = spr_player_mask;
depth = -5;
platformid = -4;
hsp_carry = 0;
scr_collision_init();
thrown = 0;
