hsp = 0;
vsp = 0;
grav = 0.5;
grounded = 0;
movespeed = 6;
image_speed = 0.35;
countdown = 120;
depth = -10;
playercollision = 1;
obj_explosion = 314;
kick = 0;
mask_index = spr_player_mask;
platformid = -4;
hsp_carry = 0;
scr_collision_init();
