scr_initenemy();
grav = 0.5;
hsp = 0;
vsp = 0;
grounded = 0;
movespeed = 2;
hitboxcreate = 0;
state = UnknownEnum.Value_134;
image_speed = 0.35;
sign_id = -4;
spr_dead = spr_piraneapple_dead;
alarm[1] = 10;
mask_index = spr_player_mask;
platformid = -4;
hsp_carry = 0;
scr_collision_init();
hamspotted = 0;
